export enum GameMode {
  UNKNOWN = "UNKNOWN",
  POINT_30 = "POINT_30",
  POINT_45 = "POINT_45",
  POINT_60 = "POINT_60",
  NORMAL = "NORMAL",
}

export enum HeroSelectionMode {
  UNKNOWN = "UNKNOWN",
  ALL_PICK = "ALL_PICK",
  ALL_RANDOM = "ALL_RANDOM",
}

export enum Team {
  UNKNOWN = "UNKNOWN",
  KONOHAGAKURE = "KONOHAGAKURE",
  OTOGAKURE = "OTOGAKURE",
  AKATSUKI = "AKATSUKI",
}

export enum PlayerState {
  UNKNOWN = "UNKNOWN",
  NOT_YET_CONNECTED = "NOT_YET_CONNECTED",
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  ABANDONED = "ABANDONED",
  LOADING = "LOADING",
  FAILED = "FAILED",
}
